function _twm(data) {
    for ( var x in data ) {
        this[x] = data[x];
        this[data[x]] = x;
    }
}

exports.__rprase = function(d,ov) {
    if ( !ov ) ov = {};
    for ( var i = 0; i < d.length; i++ ) {
        var rpos = d[i].shift();
        if ( !rpos ) throw "Failure!";
        ov[rpos] = d[i];
    }
    return ov;
}

var ERROR_CODES = new _twm({
    ERR_NOSUCHNICK: 401,
    ERR_NOSUCHSERVER: 402,
    ERR_NOSUCHCHANNEL: 403,
    ERR_CANNOTSENDTOCHAN: 404,
    ERR_TOOMANYCHANNELS: 405,
    ERR_WASNOSUCHNICK: 406,
    ERR_TOOMANYTARGETS: 407,
    ERR_NOORIGIN: 409,
    ERR_NORECIPIENT: 411,
    ERR_NOTEXTTOSEND: 412,
    ERR_NOTOPLEVEL: 413,
    ERR_WILDTOPLEVEL: 414,
    ERR_UNKNOWNCOMMAND: 421,
    ERR_NOMOTD: 422,
    ERR_NOADMININFO: 423,
    ERR_FILEERROR: 424,
    ERR_NONICKNAMEGIVEN: 431,
    ERR_ERRORNEUSNICKNAME: 432,
    ERR_NICKNAMEINUSE: 433,
    ERR_NICKCOLLISION: 436,
    ERR_USERNOTINCHANNEL: 441,
    ERR_NOTONCHANNEL: 442,
    ERR_USERONCHANNEL: 443,
    ERR_NOLOGIN: 444,
    ERR_SUMMONDISABLED: 445,
    ERR_USERSDISABLED: 446,
    ERR_NOTREGISTERED: 451,
    ERR_NEEDMOREPARAMS: 461,
    ERR_ALREADYREGISTERED: 462,
    ERR_NOPERMFORHOST: 463,
    ERR_PASSWDMISMATCH: 464,
    ERR_YOUREBANNEDCREEP: 465,
    ERR_KEYSET: 467,
    ERR_CHANNELISFULL: 471,
    ERR_UNKNOWNMODE: 472,
    ERR_INVITEONLYCHAN: 473,
    ERR_BANNEDFROMCHAN: 474,
    ERR_BADCHANNELKEY: 475,
    ERR_NOPRIVILEGES: 481,
    ERR_CHANOPRIVSNEEDED: 482,
    ERR_CANTKILLSERVER: 483,
    ERR_NOOPERHOST: 491,
    ERR_UMODEUNKNOWNFLAG: 501,
    ERR_USERSDONTMATCH: 502,
});

var RESPONSE_CODES = new _twm({
    RPL_WHOISUSER: 311,
    RPL_WHOISSERVER: 312,
    RPL_ENDOFWHOIS: 318,
    RPL_CHANNELMODEIS: 324,
    RPL_WHOISACCOUNT: 330,

    RPL_TOPIC: 332,
    RPL_TOPICWHOTIME: 333,
    RPL_WHOSPCRPL: 353, // ircu

    RPL_ENDOFNAMES: 366,
});

exports.ERROR_CODES = ERROR_CODES;
exports.RESPONSE_CODES = RESPONSE_CODES;
